name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4.1.1
        with:
          days-before-issue-stale: 360
          days-before-issue-close: 14
          stale-issue-message: 'This issue is being marked as stale due to no recent activity'
